[package]
name = "cargo-unmaintained-with-mock-github"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
cargo-unmaintained = { path = "..", features = ["__mock_github"] }
